version: "3.9"

services:
  fluentbit:
    image: fluent/fluent-bit:${FLB_IMAGE_TAG:-3.0.4}
    container_name: fluentbit
    networks:
      - log-tell
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
      - ./state:/fluent-bit/state
      - ./scripts:/fluent-bit/scripts:ro
    ports:
      - "${FLB_FORWARD_PORT:-24224}:${FLB_FORWARD_PORT:-24224}"
      - "${FLB_FORWARD_PORT:-24224}:${FLB_FORWARD_PORT:-24224}/udp"
    environment:
      HOSTNAME: ${HOSTNAME:-local-macos}
      FLB_FORWARD_PORT: ${FLB_FORWARD_PORT:-24224}
      FLB_STORAGE_TOTAL_LIMIT: ${FLB_STORAGE_TOTAL_LIMIT:-512M}
      FLB_TAIL_MEM_BUF_LIMIT: ${FLB_TAIL_MEM_BUF_LIMIT:-32M}
      LOG_INCLUDE_REGEX: ${LOG_INCLUDE_REGEX:-(?i)(info|error|exception)}
      LOG_ALERT_REGEX: ${LOG_ALERT_REGEX:-(?i)(error|exception)}
      LOG_CONTAINER_REGEX: ${LOG_CONTAINER_REGEX:-(?i)(manta-vllm-server|manta-vllm-server-2)}
      OO_HTTP_HOST: ${OO_HTTP_HOST:-host.docker.internal}
      OO_HTTP_PORT: ${OO_HTTP_PORT:-5080}
      OO_ORG: ${OO_ORG:-default}
      OO_STREAM_LOGS: ${OO_STREAM_LOGS:-logs}
      OO_STREAM_ALERTS: ${OO_STREAM_ALERTS:-logs_alerts}
      OO_AUTH_HEADER: ${OO_AUTH_HEADER:-Basic YWRtaW5AZXhhbXBsZS5jb206U3Ryb25nUGFzc3dvcmRIZXJl}
    restart: unless-stopped

networks:
  log-tell:
    name: log-tell
